apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP  # Default type, only accessible within the cluster
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
