apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80  # The port the service is exposed on externally
      targetPort: 8080  # The container port to forward to
  type: LoadBalancer  # Exposes the service externally using a cloud provider's load balancer
