apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail-deployment
  labels:
    app: promtail
spec:
  replicas: {{ .Values.promtail.replicaCount }}
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
      - name: promtail
        image: "{{ .Values.promtail.image.repository }}:{{ .Values.promtail.image.tag }}"
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        ports:
        - containerPort: {{ .Values.promtail.service.port }}