apiVersion: v1
kind: Service
metadata:
  name: router-service
spec:
  selector:
    app: router
  ports:
    - protocol: TCP
      port: 8080  # The port the service is exposed on
      targetPort: 8080  # The container port to forward to
  type: ClusterIP  # Default type, only accessible within the cluster
