apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  #By default, scrape targets every 15 seconds.
      evaluation_interval: 15s  # Evaluate rules every 15 seconds.

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              # Put your alertmanager service endpoint here

    scrape_configs:
      # Scrape configuration for Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
